version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  # Opcional: podrías añadir aquí un servicio web para Qdrant UI,
  # o Ollama si tuvieras un contenedor preparado.
  # ui:
  #   image: qdrant/qdrant-ui:latest
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - qdrant
