
[project]
name = "ai-genai-contextual"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  # Core app Chainlit
  "chainlit",
  "fastapi",
  "uvicorn",
  "httpx",
  "pydantic",
  "python-dotenv",

  # LLMs / vectores por API (ligero)
  "openai",
  "groq",
  "pinecone-client",
  "tiktoken",

  # PDFs liviano (si no usas, bórralos)
  "pypdf",
  "pdfminer.six",

  # utilidades
  "loguru",
  "rich",
]

[project.optional-dependencies]
# Todo lo pesado va aquí (NO se instala en Heroku)
heavy = [
  "transformers<5",
  "sentence-transformers<6",
  "torch",            # CPU/GPU; NO en Heroku
  "triton",
  "pymupdf",
  "unstructured",
  "pandas",
  "numpy",
  "scikit-learn",
  "pyarrow",
  "gradio",
  "streamlit",
  "langchain",
  "langchain-community",
<<<<<<< HEAD
]

[tool.uv]

=======
  "pinecone",
  "mistralai",
  "openpyxl",
  "pypdf2",
  "ragas",
  "groq",
  "asyncpg",
  "boto3",
  "translate",
]

[tool.uv]
managed = true
>>>>>>> dev
