[project]
name = "contextual-rag-asistente-normativa"
version = "0.1.0"
description = "Asistente virtual de normativa en español con fuentes en inglés con Contextual RAG + Pinecone + Chainlit + Groq"
authors = [{ name = "Laren Osorio Toribio", email = "losorio@rcp.pe" }]
requires-python = ">=3.13"

dependencies = [
  "pymupdf",
  "unstructured",
  "sentence-transformers",
  "qdrant-client",
  "langchain",
  "transformers",
  "accelerate",
  "ollama",
  "streamlit",
  "python-dotenv",
  "tqdm",
  "scikit-learn",
  "pandas",
  "huggingface_hub",
  "gradio",
  "tiktoken",
  "chainlit",
  "langchain-ollama",
  "langchain-community",
  "pinecone",
  "groq",
  "translate"
]

[tool.uv]
managed = true